# Generated by Django 6.0.3 on 2026-03-09 03:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_id', models.CharField(help_text='Internal program ID like RRB-001', max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from program ID and name for public URLs', max_length=120, unique=True)),
                ('barn_name', models.CharField(max_length=100)),
                ('registered_name', models.CharField(blank=True, max_length=150)),
                ('age', models.PositiveIntegerField(help_text='Horse age in years', validators=[django.core.validators.MinValueValidator(1)])),
                ('height_hands', models.DecimalField(decimal_places=1, help_text='Example: 15.3', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))])),
                ('sex', models.CharField(choices=[('gelding', 'Gelding'), ('mare', 'Mare'), ('stallion', 'Stallion')], default='gelding', max_length=20)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('discipline_focus', models.CharField(choices=[('barrels', 'Barrels'), ('poles', 'Poles'), ('all_around', 'All Around'), ('gymkhana', 'Gymkhana'), ('rodeo_prospect', 'Rodeo Prospect')], default='rodeo_prospect', max_length=30)),
                ('training_stage', models.CharField(choices=[('evaluation', 'Evaluation'), ('decompression', 'Decompression'), ('restart_foundation', 'Restart Foundation'), ('pattern_intro', 'Pattern Introduction'), ('started_on_pattern', 'Started on Pattern'), ('exhibitioning', 'Exhibitioning'), ('for_sale', 'For Sale'), ('sold', 'Sold')], default='evaluation', max_length=30)),
                ('temperament', models.CharField(blank=True, help_text="Short summary like 'quiet, willing, quick-footed'", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Public-facing sale or profile description')),
                ('track_notes', models.TextField(blank=True, help_text='Private/internal notes from track evaluation or intake')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_for_sale', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('is_sold', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('date_acquired', models.DateField(blank=True, null=True)),
                ('featured_photo', models.ImageField(blank=True, null=True, upload_to='horses/featured/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['program_id'],
            },
        ),
        migrations.CreateModel(
            name='HorsePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='horses/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='horses.horse')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_contacted', models.BooleanField(default=False)),
                ('horse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='horses.horse')),
            ],
            options={
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('update_date', models.DateField()),
                ('body', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_updates', to='horses.horse')),
            ],
            options={
                'ordering': ['-update_date', '-id'],
            },
        ),
    ]
