# Generated by Django 6.0.3 on 2026-03-09 04:23

import horses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Optional YouTube link for longer-form horse video'),
        ),
        migrations.AlterField(
            model_name='horse',
            name='featured_photo',
            field=models.ImageField(blank=True, help_text='Featured photo must be 5 MB or smaller.', null=True, upload_to='horses/featured/', validators=[horses.models.validate_featured_photo_size]),
        ),
        migrations.AlterField(
            model_name='horse',
            name='program_id',
            field=models.CharField(blank=True, help_text='Auto-generated if left blank, e.g. RRB-001', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='horse',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated from program ID and barn name for public URLs', max_length=120, unique=True),
        ),
    ]
