# Generated by Django 6.0.3 on 2026-03-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0002_horse_youtube_url_alter_horse_featured_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
