# Generated by Django 6.0.3 on 2026-03-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0003_horse_is_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horse',
            name='is_new',
        ),
        migrations.AddField(
            model_name='horse',
            name='flyer_image',
            field=models.ImageField(blank=True, help_text='Auto-generated Facebook flyer image.', null=True, upload_to='flyers/'),
        ),
    ]
