# Generated by Django 6.0.3 on 2026-03-13 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0004_remove_horse_is_new_horse_flyer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorseEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('previous_owner', models.CharField(blank=True, max_length=255)),
                ('purchase_source', models.CharField(blank=True, help_text='Auction, private seller, breeder, trainer, etc.', max_length=255)),
                ('body_condition', models.CharField(blank=True, max_length=100)),
                ('soundness_observations', models.TextField(blank=True)),
                ('temperament_notes', models.TextField(blank=True)),
                ('ground_manners', models.TextField(blank=True)),
                ('handling_behavior', models.TextField(blank=True)),
                ('training_level', models.CharField(blank=True, max_length=255)),
                ('discipline_exposure', models.TextField(blank=True)),
                ('behavioral_notes', models.TextField(blank=True)),
                ('veterinary_notes', models.TextField(blank=True)),
                ('farrier_status', models.CharField(blank=True, max_length=255)),
                ('vaccination_status', models.CharField(blank=True, max_length=255)),
                ('dental_status', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('horse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='horses.horse')),
            ],
            options={
                'verbose_name': 'Horse Intake Evaluation',
                'verbose_name_plural': 'Horse Intake Evaluations',
                'ordering': ['horse__program_id'],
            },
        ),
    ]
